import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF7FAFC),
      body: Center(
        child: SingleChildScrollView(
          child: Container(
            constraints: const BoxConstraints(maxWidth: 700),
            margin: const EdgeInsets.symmetric(vertical: 32, horizontal: 12),
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.07),
                  blurRadius: 24,
                  offset: const Offset(0, 4),
                ),
              ],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Center(
                  child: Column(
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.circular(16),
                        child: Image.asset(
                          'assets/logo.png',
                          width: 72,
                          height: 72,
                          fit: BoxFit.cover,
                        ),
                      ),
                      const SizedBox(height: 12),
                      const Text(
                        'The Sabaq App',
                        style: TextStyle(
                          fontSize: 28,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF2A6F97),
                        ),
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        'A powerful tool for Qaris and Madrassas to manage student records and track Quranic learning progress.',
                        style: TextStyle(
                          fontSize: 16,
                          color: Color(0xFF555555),
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 32),
                const Text(
                  'Privacy Policy',
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF184E77),
                  ),
                ),
                const SizedBox(height: 8),
                const Text(
                  'Effective Date: [Insert Date]',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Thank you for choosing The Sabaq App. Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your information when you use our app.',
                  style: TextStyle(fontSize: 16),
                ),
                const SizedBox(height: 20),
                _sectionTitle('1. Information We Collect'),
                _subSection('a. User-Provided Information:'),
                _bullets([
                  'When you create an account or log in, we may collect your name, email address, and password.',
                  'When you add students (Talba) and their records, we collect information such as student names, progress, and performance data.',
                ]),
                _subSection('b. Automatically Collected Information:'),
                _bullets([
                  'We may collect device information (such as device type, operating system, and unique device identifiers) for security and app improvement purposes.',
                  'Usage data, such as how you interact with the app, may be collected to help us improve features and user experience.',
                ]),
                _sectionTitle('2. How We Use Your Information'),
                _bullets([
                  'Provide and improve app features, such as managing student records and generating reports.',
                  'Enable secure login and account management.',
                  'Allow you to back up and restore your data across devices.',
                  'Generate and share PDF reports with parents or management, as requested by you.',
                ]),
                _sectionTitle('3. Data Sharing and Disclosure'),
                _bullets([
                  'We do not sell or share your personal information with third parties except as required by law or with your explicit consent.',
                  'PDF reports generated by the app are only shared by you, at your discretion, with parents or management.',
                ]),
                _sectionTitle('4. Data Security'),
                _bullets([
                  'We use industry-standard security measures to protect your data, including secure login and encrypted backups.',
                  'Your data is stored securely on your device and, if you use the backup feature, in a secure cloud storage solution.',
                ]),
                _sectionTitle('5. Data Retention'),
                _bullets([
                  'Your data is retained as long as your account is active or as needed to provide you with our services.',
                  'You can delete your account or student records at any time from within the app.',
                ]),
                _sectionTitle("6. Children's Privacy"),
                _bullets([
                  'The Sabaq App is intended for use by Qaris, Madrassas, and educators. We do not knowingly collect personal information from children under 13 without parental consent.',
                ]),
                _sectionTitle('7. Your Rights'),
                _bullets([
                  'You can access, update, or delete your information at any time through the app settings.',
                  'If you have any questions or requests regarding your data, please contact us at: info@itartificer.com',
                ]),
                _sectionTitle('8. Changes to This Policy'),
                _bullets([
                  'We may update this Privacy Policy from time to time. We will notify you of any significant changes by posting the new policy on this page.',
                ]),
                const SizedBox(height: 20),
                const Text(
                  'Contact Us:',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 4),
                const SelectableText(
                  'If you have any questions about this Privacy Policy, please contact us at: info@itartificer.com',
                  style: TextStyle(fontSize: 16),
                ),
                const SizedBox(height: 32),
                const Divider(),
                const SizedBox(height: 8),
                const Center(
                  child: Text(
                    '© 2024 The Sabaq App. All rights reserved.',
                    style: TextStyle(color: Colors.grey, fontSize: 14),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  static Widget _sectionTitle(String text) => Padding(
        padding: const EdgeInsets.only(top: 20, bottom: 8),
        child: Text(
          text,
          style: const TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: Color(0xFF277DA1),
          ),
        ),
      );

  static Widget _subSection(String text) => Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 4),
        child: Text(
          text,
          style: const TextStyle(
            fontWeight: FontWeight.w600,
            fontSize: 15,
          ),
        ),
      );

  static Widget _bullets(List<String> items) => Padding(
        padding: const EdgeInsets.only(left: 16, bottom: 8),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: items
              .map((e) => Padding(
                    padding: const EdgeInsets.only(bottom: 4),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text('• ', style: TextStyle(fontSize: 16)),
                        Expanded(
                          child: Text(
                            e,
                            style: const TextStyle(fontSize: 16),
                          ),
                        ),
                      ],
                    ),
                  ))
              .toList(),
        ),
      );
} 